# Generated by Django 4.2.9 on 2024-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customername', models.CharField(default='', max_length=25)),
                ('gender', models.CharField(default='MALE', max_length=6)),
                ('areatype', models.CharField(max_length=5)),
                ('customerphoto', models.ImageField(upload_to='photo/')),
            ],
            options={
                'db_table': 'reading_customer',
            },
        ),
    ]
